theme: jekyll-theme-minimal
title: Tugay KAÇAK's homepage
description: Bookmark this to keep an eye on my project updates!
author:
  name: "Tugay KAÇAK"
  bio: "PhD Candidate"
  avatar: "Will be updated"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/tugay-kacak-7265921b2/"
    - label: "ResearchGate"
      url: "https://www.researchgate.net/profile/Tugay-Kacak-2"
header_pages:
  - about.md
